# Generated by Django 2.0.5 on 2018-05-14 19:38

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connections', '0002_auto_20180512_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectiontable',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='connectiontable',
            name='direction',
            field=models.CharField(choices=[('to partner', 'to partner'), ('from partner', 'from partner')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='connectiontable',
            name='message_type',
            field=models.CharField(choices=[('movement', 'movement'), ('execution', 'execution'), ('financial', 'financial')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='connectiontable',
            name='status',
            field=models.CharField(choices=[('awaiting approval', 'awaiting approval'), ('approved', 'approved'), ('rejected', 'rejected')], default='awaiting approval', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='connectiontable',
            unique_together={('user', 'message_type', 'direction', 'client')},
        ),
    ]
