# Generated by Django 2.0.5 on 2018-05-15 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_auto_20180514_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectiontable',
            options={'ordering': ('client', 'direction')},
        ),
    ]
