# Generated by Django 2.0.5 on 2018-05-11 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(default='', max_length=100, unique=True)),
                ('gatekeeper_id', models.IntegerField(default=0, unique=True)),
                ('business_name', models.CharField(default='', max_length=100, unique=True)),
                ('address', models.CharField(default='', max_length=100)),
                ('town', models.CharField(default='', max_length=50)),
                ('county', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=30)),
                ('post_code', models.CharField(default='', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
