# Generated by Django 2.0.5 on 2018-05-12 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=100)),
                ('town', models.CharField(default='', max_length=50)),
                ('county', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=30)),
                ('post_code', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='farmuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='farmuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='farmuser',
            name='county',
        ),
        migrations.RemoveField(
            model_name='farmuser',
            name='post_code',
        ),
        migrations.RemoveField(
            model_name='farmuser',
            name='town',
        ),
        migrations.AlterField(
            model_name='farmuser',
            name='gatekeeper_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
