# Generated by Django 2.0.5 on 2018-05-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180512_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmuser',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
    ]
